### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ondra-vaic** [DaCookie/mindwave-unity#3]
Hello,

I am creating a game that is controlled with an eye-tracker and a Mindwave mobile for my bachelor thesis. The game will later be used in hospitals for therapy.  I really like this package, it's super simple to use, can I use it in the thesis?

Have a nice day,
Ondřej Vaic

**Comment by hubertgdev** [comment]
Hi there!
I developped this package a long time ago as a utility for a project, and I didn't update it since. But sure you can use this package in your project ! ;)
What version of Unity are you using ? I may do some updates and compatibility checks on this package for the occasion...

**Comment by ondra-vaic** [comment]
Hi thanks a lot :). It works just fine for me on 2019.2.10. I think I only
had to make sure that the is set to Scripting Runtime Version is 4.0.
Stay safe :)

ne 12. 4. 2020 v 21:32 odesílatel Hubert GROSSIN <notifications@github.com>
napsal:

**Comment by hubertgdev** [comment]
Yup, I updated the documentation about the API Compatibility Level setting. I also fixed an error I saw in two scripts:
- `Assets/Plugins/MindwaveUnity/Core/MindwaveHelper.cs`
- `Assets/Plugins/MindwaveUnity/Data/MindwaveDataESenseModel.cs`

You can get these scripts, and you are ready to go ;)
